# https://taskfile.dev

version: '3'

vars:
  ALL: ./...

env:
  MODULE_PATH: github.com/barnowlsnest/go-datalib

tasks:
  go-update:
    cmds:
      - go mod tidy

  go-build:
    cmds:
      - go build '{{.ALL}}'

  go-fmt:
    cmds:
      - go fmt '{{.ALL}}'

  go-vet:
    cmds:
      - go vet '{{.ALL}}'

  go-test:
    cmds:
      - go test -cover '{{.ALL}}'

  go-bench:
    desc: Run benchmarks with memory stats
    cmds:
      - go test -bench=. -benchmem '{{.ALL}}'

  go-bench-serial:
    desc: Run serial package benchmarks
    cmds:
      - go test -bench=. -benchmem ./pkg/serial

  go-lint:
    cmds:
      - golangci-lint run --fix

  sanity:
    deps:
      - go-update
    cmds:
      - task: go-fmt
      - task: go-vet
      - task: go-lint
      - task: go-test

  build:
    deps:
      - sanity
    cmds:
      - task: go-build

  release:major:
    deps:
      - build
    cmds:
      - ./scripts/release.sh major

  release:minor:
    desc: Create a minor release
    deps:
      - build
    cmds:
      - ./scripts/release.sh minor

  release:patch:
    desc: Create a patch release
    deps:
      - build
    cmds:
      - ./scripts/release.sh patch

