# https://taskfile.dev

version: '3'

vars:
  ALL: ./...
  COVERAGE_THRESHOLD: 80  # Minimum code coverage percentage required

env:
  MODULE_PATH: github.com/barnowlsnest/go-datalib

tasks:
  go-update:
    cmds:
      - go mod tidy

  go-build:
    cmds:
      - go build '{{.ALL}}'

  go-fmt:
    cmds:
      - go fmt '{{.ALL}}'

  go-vet:
    cmds:
      - go vet '{{.ALL}}'

  go-test:
    cmds:
      - go test -cover '{{.ALL}}'

  go-coverage:
    desc: Check code coverage and ensure it meets minimum thresholds
    cmds:
      - |
        echo "Checking code coverage (minimum threshold: {{.COVERAGE_THRESHOLD}}%)..."
        go test -coverprofile=/tmp/coverage.out '{{.ALL}}'
        go tool cover -func=/tmp/coverage.out | tail -1

        # Extract total coverage percentage
        TOTAL_COV=$(go tool cover -func=/tmp/coverage.out | grep total | awk '{print $3}' | sed 's/%//')

        # Check if coverage meets minimum threshold
        if [ $(echo "$TOTAL_COV < {{.COVERAGE_THRESHOLD}}" | bc) -eq 1 ]; then
          echo "❌ Coverage check failed: ${TOTAL_COV}% is below minimum threshold of {{.COVERAGE_THRESHOLD}}%"
          exit 1
        fi

        echo "✅ Coverage check passed: ${TOTAL_COV}% (threshold: {{.COVERAGE_THRESHOLD}}%)"

  go-bench:
    desc: Run benchmarks with memory stats
    cmds:
      - go test -bench=. -benchmem '{{.ALL}}'

  go-bench-serial:
    desc: Run serial package benchmarks
    cmds:
      - go test -bench=. -benchmem ./pkg/serial

  go-lint:
    cmds:
      - golangci-lint run --fix

  sanity:
    deps:
      - go-update
    cmds:
      - task: go-fmt
      - task: go-vet
      - task: go-lint
      - task: go-test
      - task: go-coverage

  build:
    deps:
      - sanity
    cmds:
      - task: go-build

  release:major:
    deps:
      - build
    cmds:
      - ./scripts/release.sh major

  release:minor:
    desc: Create a minor release
    deps:
      - build
    cmds:
      - ./scripts/release.sh minor

  release:patch:
    desc: Create a patch release
    deps:
      - build
    cmds:
      - ./scripts/release.sh patch

